version: '3.5'

services:
  postgres:
    container_name: postgres_dev
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-abc123}
      TZ: "America/Costa_Rica"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "54320:5432"
    restart: always
  
  pgadmin:
    container_name: pgadmin_dev
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-50500}:80"
    restart: always

volumes:
    postgres:
    pgadmin: